kumuluzee:
  datasources:
    - jndi-name: jdbc/RsobookDS
      connection-url: jdbc:postgresql://localhost:5432/rsobook-user_wall
      username: postgres
      password: root
      max-pool-size: 10